(()=>{
'use strict';
const categories=[{"id":"identite-visuelle","fr":"Identité visuelle","en":"Visual identity"},{"id":"edition","fr":"Édition","en":"Editorial"},{"id":"poster","fr":"Poster","en":"Poster"},{"id":"photographie","fr":"Photographie","en":"Photography"},{"id":"art-plastique","fr":"Art plastique","en":"Fine art"}];
let sourceSnapshot='';
const $=id=>document.getElementById(id);let lang=document.documentElement.lang,records=[],current=null,assets=new Map(),busy=false,dirty=false,objectURLs=[];
const t=(fr,en)=>lang==='en'?en:fr;const value=x=>x?.[lang]||x?.fr||x?.en||'';
const clean=()=>({id:'',title:{fr:'',en:''},categoryId:'identite-visuelle',category:{fr:'Identité visuelle',en:'Visual identity'},description:{fr:'',en:''},images:[],published:true});
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(s){$('status').textContent=s}
function choose(p){objectURLs.forEach(u=>URL.revokeObjectURL(u));objectURLs=[];assets.clear();current=structuredClone(p);for(const f of ['title','description'])for(const l of ['fr','en'])$(f+'-'+l).value=current[f]?.[l]||'';$('category-id').value=current.categoryId||'identite-visuelle';$('delete-project').hidden=!current.id;$('published').checked=current.published;dirty=false;$('download-next').hidden=true;renderImages();status('')}
function sync(){for(const f of ['title','description'])for(const l of ['fr','en'])current[f][l]=$(f+'-'+l).value.trim();current.categoryId=$('category-id').value;const c=categories.find(c=>c.id===current.categoryId);current.category={fr:c.fr,en:c.en};current.published=$('published').checked;}
function options(){for(const o of $('category-id').children){const c=categories.find(c=>c.id===o.value);if(c)o.textContent=value(c)}const selected=$('select-project').value;$('select-project').replaceChildren();const opt=document.createElement('option');opt.value='';opt.textContent=t('+ Nouveau projet','+ New project');$('select-project').append(opt);for(const p of records){const o=document.createElement('option');o.value=p.id;o.textContent=value(p.title);$('select-project').append(o)}$('select-project').value=selected;}
function renderImages(){const list=$('image-list');list.replaceChildren();current.images.forEach((im,i)=>{const row=document.createElement('div');row.className='image-editor';const image=document.createElement('img');image.src=im.preview||im.src;image.alt=value(im.alt)||'';const content=document.createElement('div'),label=document.createElement('label');const title=document.createElement('span');title.textContent=i===0?t('Couverture','Cover'):t('Image ','Image ')+(i+1);const input=document.createElement('input');input.value=value(im.alt);input.placeholder=t('Description de l’image','Image description');input.addEventListener('input',()=>{im.alt[lang]=input.value;dirty=true});label.append(title,input);content.append(label);const actions=document.createElement('div');actions.className='actions';for(const [name,delta] of [[t('Monter','Move up'),-1],[t('Descendre','Move down'),1],[t('Retirer','Remove'),0]]){const b=document.createElement('button');b.type='button';b.textContent=name;b.disabled=delta===-1?i===0:delta===1?i===current.images.length-1:false;b.addEventListener('click',()=>{if(!delta){assets.delete(im.src);current.images.splice(i,1)}else [current.images[i],current.images[i+delta]]=[current.images[i+delta],current.images[i]];dirty=true;renderImages()});actions.append(b)}content.append(actions);row.append(image,content);list.append(row)})}
$('select-project').addEventListener('change',()=>{if(dirty&&!confirm(t('Quitter ce projet ? Vos modifications non téléchargées seront perdues.','Leave this project? Undownloaded changes will be lost.'))){$('select-project').value=current.id;return}choose(records.find(p=>p.id===$('select-project').value)||clean())});
$('project-form').addEventListener('input',()=>dirty=true);
$('images').addEventListener('change',e=>{let size=[...assets.values()].reduce((n,f)=>n+f.size,0);for(const f of Array.from(e.target.files)){if(!['image/jpeg','image/png','image/webp','image/gif'].includes(f.type)||f.size>15*1024*1024){status(t('Image refusée : ','Image rejected: ')+f.name);continue}if(size+f.size>50*1024*1024||current.images.length>=30){status(t('Limite de 30 images ou 50 Mo atteinte.','Limit of 30 images or 50 MB reached.'));break}size+=f.size;const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'}[f.type];const src='uploads/'+crypto.randomUUID()+'.'+ext;assets.set(src,f);const preview=URL.createObjectURL(f);objectURLs.push(preview);current.images.push({src,alt:{fr:'',en:''},preview});dirty=true}e.target.value='';renderImages()});
function page(p){const imgs=p.images.map((im,i)=>`<button class="gallery-item" type="button" aria-label="${esc(im.alt.fr||p.title.fr)}"><img src="${esc(im.src)}" alt="${esc(im.alt.fr||p.title.fr)}" loading="${i===0?'eager':'lazy'}"></button>`).join('');return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title.fr)} — Sara Asadnia</title><meta name="description" content="${esc(p.description.fr.slice(0,160))}"><link rel="icon" href="favicon.svg"><link rel="stylesheet" href="portfolio.css"><script src="portfolio.js" defer></script></head><body><a class="skip" href="#main">Aller au contenu / Skip to content</a><header><a class="brand" href="index.html">Sara Asadnia<span>Design graphique / Graphic design</span></a><nav><a href="index.html#work" data-fr="Projets" data-en="Work">Projets</a><a href="#contact">Contact</a><div class="language"><button data-language="fr" aria-pressed="true">FR</button><button data-language="en" aria-pressed="false">EN</button></div></nav></header><main id="main" class="project-page" data-project-id="${p.id}"><a class="back" href="index.html#work" data-fr="Tous les projets" data-en="All projects">Tous les projets</a><div class="project-intro"><span class="eyebrow" id="project-category">${esc(p.category.fr)}</span><h1 id="project-title">${esc(p.title.fr)}</h1><p id="project-description">${esc(p.description.fr)}</p></div><div class="project-gallery" id="project-gallery">${imgs}</div><a class="back end-back" href="index.html#work" data-fr="Retour aux projets" data-en="Back to work">Retour aux projets</a></main><footer id="contact"><a href="mailto:fatemeh.asadnia55@gmail.com">Email</a><div class="footer-bottom"><span>© Sara Asadnia</span><a href="manage.html" data-fr="Gérer les projets" data-en="Manage projects">Gérer les projets</a></div></footer></body></html>`;}
// Store-only ZIP: files stay on this device until the user uploads them to GitHub.
const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let j=0;j<8;j++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0}
function crc(bytes){let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
const enc=new TextEncoder();function header(size){const a=new Uint8Array(size);return[a,new DataView(a.buffer)]}
function zip(files){const parts=[],central=[];let offset=0;for(const f of files){const name=enc.encode(f.name),data=f.bytes,checksum=crc(data);let[h,v]=header(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,0x21,true);v.setUint32(14,checksum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);parts.push(h,name,data);let[c,d]=header(46);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint16(14,0x21,true);d.setUint32(16,checksum,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,name.length,true);d.setUint32(42,offset,true);central.push(c,name);offset+=h.length+name.length+data.length}const centralSize=central.reduce((s,a)=>s+a.length,0);let[end,v]=header(22);v.setUint32(0,0x06054b50,true);v.setUint16(8,files.length,true);v.setUint16(10,files.length,true);v.setUint32(12,centralSize,true);v.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'})}
$('project-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;sync();if(!current.title.fr||!current.images.length){status(t('Ajoutez un titre français et au moins une image.','Add a French title and at least one image.'));return}busy=true;$('fields').disabled=true;status(t('Préparation du dossier…','Preparing the folder…'));try{await checkFresh();const p=structuredClone(current);p.id=p.id||'projet-'+crypto.randomUUID();p.images=p.images.map(({src,alt})=>({src,alt}));const updated=current.id?records.map(r=>r.id===p.id?p:r):[p,...records];const files=[{name:'projects.json',bytes:enc.encode(JSON.stringify(updated,null,2))},{name:p.id+'.html',bytes:enc.encode(page(p))}];for(const [name,f]of assets)files.push({name,bytes:new Uint8Array(await f.arrayBuffer())});const blob=zip(files),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=p.id+'-portfolio.zip';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status(t('Dossier téléchargé. Envoyez-le sur GitHub pour publier vos changements.','Folder downloaded. Upload it to GitHub to publish your changes.'));$('download-next').hidden=false;dirty=false;}catch(e){status(e.message||t('Impossible de préparer le dossier. Vos données sont toujours ici.','Could not prepare the folder. Your data is still here.'));console.error(e)}finally{busy=false;$('fields').disabled=false}});
async function checkFresh(){const r=await fetch('projects.json',{cache:'no-store'});if(!r.ok)throw Error(t('Impossible de vérifier le site. Réessayez.','Unable to check the site. Please retry.'));if(JSON.stringify(await r.json())!==sourceSnapshot)throw Error(t('Le site a changé. Publiez ou sauvegardez vos modifications, puis rechargez cette page avant de continuer.','The site has changed. Save your edits and reload this page before continuing.'));}
$('delete-project').addEventListener('click',async()=>{if(busy||!current?.id)return;if(!confirm(t('Retirer « '+value(current.title)+' » du portfolio ? Les fichiers images restent dans GitHub.','Remove “'+value(current.title)+'” from the portfolio? Image files stay in GitHub.')))return;busy=true;$('fields').disabled=true;try{await checkFresh();const updated=records.filter(p=>p.id!==current.id);const blob=zip([{name:'projects.json',bytes:enc.encode(JSON.stringify(updated,null,2))}]);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=current.id+'-suppression.zip';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);$('download-next').hidden=false;status(t('Suppression préparée. Décompressez le ZIP et envoyez projects.json sur GitHub pour la publier.','Deletion prepared. Unzip the download and upload projects.json to GitHub to publish it.'));dirty=false;}catch(e){status(e.message||t('Suppression impossible. Réessayez.','Could not prepare deletion. Please retry.'));}finally{busy=false;$('fields').disabled=false;}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});document.addEventListener('portfolio-language',e=>{lang=e.detail;options();if(current)renderImages()});
fetch('projects.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(!Array.isArray(data))throw Error();records=data;sourceSnapshot=JSON.stringify(data);options();choose(clean());$('select-project').disabled=false;$('fields').disabled=false}).catch(()=>status(t('Chargement impossible. Rechargez la page avant de préparer des fichiers.','Unable to load projects. Reload the page before preparing files.')));
})();
