(()=>{
'use strict';
let lang=new URLSearchParams(location.search).get('lang')||'fr';try{if(!new URLSearchParams(location.search).has('lang'))lang=localStorage.getItem('portfolio-language')||'fr'}catch{}if(!['fr','en'].includes(lang))lang='fr';
let records=[];const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e};
const text=(v)=>typeof v==='string'?v:(v?.[lang]||v?.fr||v?.en||'');
const validSrc=s=>typeof s==='string'&&!/^(?:[a-z]+:|\/\/|\/)/i.test(s)&&!s.split('/').includes('..');
function language(next){lang=next;document.documentElement.lang=lang;try{localStorage.setItem('portfolio-language',lang)}catch{}document.querySelectorAll('[data-fr][data-en]').forEach(e=>e.textContent=e.dataset[lang]);document.querySelectorAll('[data-language]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.language===lang)));if(records.length)render();document.dispatchEvent(new CustomEvent('portfolio-language',{detail:lang}));}
function render(){const grid=document.getElementById('projects');if(grid){grid.replaceChildren();records.filter(p=>p.published&&p.images?.length).forEach((p,i)=>{const a=node('a','project-card');a.href=encodeURIComponent(p.id)+'.html?lang='+lang;const cover=node('div','cover'),im=node('img');if(validSrc(p.images[0].src))im.src=p.images[0].src;im.alt=text(p.images[0].alt)||text(p.title);im.loading=i<2?'eager':'lazy';im.decoding='async';cover.append(im);const meta=node('div','card-meta');meta.append(node('h3','',text(p.title)),node('span','project-number',String(i+1).padStart(2,'0')),node('p','',text(p.category)));a.append(cover,meta);grid.append(a)});document.getElementById('project-count').textContent=String(grid.children.length).padStart(2,'0')}
 const main=document.querySelector('[data-project-id]');if(main){const p=records.find(p=>p.id===main.dataset.projectId);if(!p)return;document.title=text(p.title)+' — Sara Asadnia';document.getElementById('project-title').textContent=text(p.title);document.getElementById('project-category').textContent=text(p.category);document.getElementById('project-description').textContent=text(p.description);const gallery=document.getElementById('project-gallery');gallery.replaceChildren();p.images.forEach((im,i)=>{const b=node('button','gallery-item');b.type='button';b.setAttribute('aria-label',text(im.alt)||text(p.title));const img=node('img');if(validSrc(im.src))img.src=im.src;img.alt=text(im.alt)||text(p.title);img.loading=i===0?'eager':'lazy';img.decoding='async';b.append(img);gallery.append(b)})}}
 document.querySelectorAll('[data-language]').forEach(b=>b.addEventListener('click',()=>language(b.dataset.language)));language(lang);
 fetch('projects.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(!Array.isArray(data))throw Error();records=data;render()}).catch(()=>{/* Server-rendered project links and images remain usable. */});
 const dialog=node('dialog','lightbox');dialog.setAttribute('aria-label','Galerie / Gallery');const close=node('button','close');close.type='button';close.textContent='Fermer / Close';const image=node('img'),controls=node('div','lightbox-controls'),prev=node('button','', 'Précédent / Previous'),counter=node('span'),next=node('button','','Suivant / Next');prev.type=next.type='button';controls.append(prev,counter,next);dialog.append(close,image,controls);document.body.append(dialog);let current=0,images=[],opener=null;function show(){image.src=images[current].src;image.alt=images[current].alt;counter.textContent=(current+1)+' / '+images.length;prev.disabled=next.disabled=images.length<2}function move(n){current=(current+n+images.length)%images.length;show()}
 document.addEventListener('click',e=>{const b=e.target.closest?.('.gallery-item');if(!b)return;images=[...document.querySelectorAll('.gallery-item img')];current=images.indexOf(b.querySelector('img'));opener=b;show();dialog.showModal();document.body.style.overflow='hidden';close.focus()});close.addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.style.overflow='';opener?.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});prev.addEventListener('click',()=>move(-1));next.addEventListener('click',()=>move(1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}if(e.key==='ArrowRight'){e.preventDefault();move(1)}});
})();
